// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChADffrQlCxtjfrRUFKR8REKBfXqeoTVI',
    appId: '1:200924479038:web:e752711d375663a9645b6f',
    messagingSenderId: '200924479038',
    projectId: 'raijin-anime',
    authDomain: 'raijin-anime.firebaseapp.com',
    storageBucket: 'raijin-anime.appspot.com',
    measurementId: 'G-Q5RD62VGR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5aTnJiEgqUSZeJkWCMU27IZK8QXk4_d0',
    appId: '1:200924479038:android:2ae95da84ea29591645b6f',
    messagingSenderId: '200924479038',
    projectId: 'raijin-anime',
    storageBucket: 'raijin-anime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZwBW23cwav-CVKN4KxwkwLgjeuJDjIU',
    appId: '1:200924479038:ios:352fb5fd1cfb8baf645b6f',
    messagingSenderId: '200924479038',
    projectId: 'raijin-anime',
    storageBucket: 'raijin-anime.appspot.com',
    iosBundleId: 'com.example.raijin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANZwBW23cwav-CVKN4KxwkwLgjeuJDjIU',
    appId: '1:200924479038:ios:2211b3fcbdb45586645b6f',
    messagingSenderId: '200924479038',
    projectId: 'raijin-anime',
    storageBucket: 'raijin-anime.appspot.com',
    iosBundleId: 'com.example.raijin.RunnerTests',
  );
}
